import language from '../languages/index';
export const onBoardingScreen = [
  {
    mainColor: '#1CD9C3',
    transparentColor: '#22E1CE',
    imageColor: '#2BE7D8',
    boxColor: '#1FA090',
    iconColor: '#ffff',
    titleText: language.t('onBoardingTitle1'),
    description: language.t('onBoardingDes1'),
    img: require('../assets/onboarding1.png'),
    icon: require('../assets/caveron.png'),
  },
  {
    mainColor: '#F75A59',
    transparentColor: '#F9797650',
    imageColor: '#F97976',
    boxColor: '#EA3736',
    titleText: language.t('onBoardingTitle2'),
    description: language.t('onBoardingDes2'),
    img: require('../assets/onboarding2.png'),
    icon: require('../assets/caveron.png'),
    iconColor: '#A9A9A9',
  },
  {
    mainColor: '#8A8A8A',
    transparentColor: '#9A9A9A',
    imageColor: '#A9A9A9',
    boxColor: '#707070',
    iconColor: '#000',
    titleText: language.t('onBoardingTitle3'),
    description: language.t('onBoardingDes3'),
    img: require('../assets/onboarding3.png'),
    icon: require('../assets/done.png'),
  },
];

export const userProfiles = [
  {
    name: 'Ali Abdullah',
    userId: '1',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 50,
    time: '2 min ago',
    message: 'Hey, how are you doing?',
  },
  {
    name: 'Fatima Khan',
    userId: '2',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 30,
    time: '5 min ago',
    message: 'Looking forward to our meeting.',
  },
  {
    name: 'Ahmed Raza',
    userId: '3',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 45,
    time: '10 min ago',
    message: 'Can you share the files?',
  },
  {
    name: 'Sana Malik',
    userId: '4',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 25,
    time: '20 min ago',
    message: 'Thank you for the update!',
  },
  {
    name: 'Zain Ul Abidin',
    userId: '5',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 60,
    time: '30 min ago',
    message: 'Let me know when you’re free.',
  },
  {
    name: 'Ayesha Tariq',
    userId: '6',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 15,
    time: '45 min ago',
    message: 'I’m running late, see you soon!',
  },
  {
    name: 'Bilal Ahmed',
    userId: '7',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 40,
    time: '1 hour ago',
    message: 'What time is the event?',
  },
  {
    name: 'Maria Hussain',
    userId: '8',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 35,
    time: '2 hours ago',
    message: 'I’ll send the details shortly.',
  },
  {
    name: 'Usman Farooq',
    userId: '9',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 20,
    time: '3 hours ago',
    message: 'Can we reschedule our call?',
  },
  {
    name: 'Rabia Shaikh',
    userId: '10',
    userImg: require('../assets/userImage.jpg'),
    from_num_message: 55,
    time: '1 day ago',
    message: 'Looking forward to your reply.',
  },
];
